# Generated by Django 4.2.17 on 2025-01-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ecoactivity",
            options={"ordering": ["-date"], "verbose_name_plural": "Eco Activities"},
        ),
        migrations.AlterModelOptions(
            name="sustainabilitygoal",
            options={"ordering": ["deadline"]},
        ),
        migrations.RemoveField(
            model_name="ecoactivity",
            name="created_at",
        ),
        migrations.AddField(
            model_name="ecoactivity",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ecoactivity",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sustainabilitygoal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="ecoactivity",
            name="category",
            field=models.CharField(
                choices=[
                    ("ENERGY", "Energy Consumption"),
                    ("WATER", "Water Usage"),
                    ("WASTE", "Waste Management"),
                    ("TRANSPORT", "Transportation"),
                    ("RECYCLING", "Recycling"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ecoactivity",
            name="value",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="sustainabilitygoal",
            name="current_value",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="sustainabilitygoal",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sustainabilitygoal",
            name="target_value",
            field=models.FloatField(),
        ),
    ]
