# Generated by Django 4.2.17 on 2025-01-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0004_subscriptionplan_usersubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
